export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET = 'USER_SET';
export const USER_FETCHING = 'USER_FETCHING';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';
export const USER_UNAUTHORIZED = 'USER_UNAUTHORIZED';
